define([],function(){
	var mappings = {
		"id" : "id",
		"Name" : "Name",
		"Description" : "Description",
		"Type_Id" : "Type_Id",
		"Organization_id" : "Organization_id",
		"Taxid" : "Taxid",
		"Membership_id" : "Membership_id",
		"Sequence" : "Sequence",
		"Value" : "Value",
		"Extension" : "Extension",
		"IsPreferredContactMethod" : "IsPreferredContactMethod",
		"PreferredContactTime" : "PreferredContactTime",
		"createdby" : "createdby",
		"modifiedby" : "modifiedby",
		"createdts" : "createdts",
		"lastmodifiedts" : "lastmodifiedts",
		"synctimestamp" : "synctimestamp",
		"softdeleteflag" : "softdeleteflag",
		"DurationOfStay" : "DurationOfStay",
		"IsPrimary" : "IsPrimary",
		"contactnumber" : "contactnumber",
		"emailid" : "emailid",
		"addressLine1" : "addressLine1",
		"addressLine2" : "addressLine2",
		"zipCode" : "zipCode",
		"cityName" : "cityName",
		"country" : "country",
		"state" : "state",
		"Email" : "Email",
		"Tin" : "Tin",
		"searchType" : "searchType",
		"errorCode" : "errorCode",
		"errorMessage" : "errorMessage",
		"success" : "success",
		"Phone" : "Phone",
		"searchString" : "searchString",
		"order" : "order",
		"sortBy" : "sortBy",
		"offset" : "offset",
		"limit" : "limit",
		"Type" : "Type",
		"Communication" : "Communication",
		"Address" : "Address",
		"Owner" : "Owner",
		"Membership" : "Membership",
		"AccountsList" : "AccountsList",
		"EAgreementRequired" : "EAgreementRequired",
		"LastName" : "LastName",
		"MiddleName" : "MiddleName",
		"FirstName" : "FirstName",
		"status" : "status",
		"Lastlogintime" : "Lastlogintime",
		"role_id" : "role_id",
		"DOB" : "DOB",
		"Ssn" : "Ssn",
		"TypeName" : "TypeName",
		"DrivingLicenseNumber" : "DrivingLicenseNumber",
		"DateOfBirth" : "DateOfBirth",
		"isExists" : "isExists",
		"Account_id" : "Account_id",
		"accountID" : "accountID",
		"addressId" : "addressId",
	};
	Object.freeze(mappings);
	
	var typings = {
		"id" : "string",
		"Name" : "string",
		"Description" : "string",
		"Type_Id" : "string",
		"Organization_id" : "string",
		"Taxid" : "string",
		"Membership_id" : "string",
		"Sequence" : "string",
		"Value" : "string",
		"Extension" : "string",
		"IsPreferredContactMethod" : "string",
		"PreferredContactTime" : "string",
		"createdby" : "string",
		"modifiedby" : "string",
		"createdts" : "string",
		"lastmodifiedts" : "string",
		"synctimestamp" : "string",
		"softdeleteflag" : "string",
		"DurationOfStay" : "string",
		"IsPrimary" : "string",
		"contactnumber" : "string",
		"emailid" : "string",
		"addressLine1" : "string",
		"addressLine2" : "string",
		"zipCode" : "string",
		"cityName" : "string",
		"country" : "string",
		"state" : "string",
		"Email" : "string",
		"Tin" : "string",
		"searchType" : "string",
		"errorCode" : "string",
		"errorMessage" : "string",
		"success" : "string",
		"Phone" : "string",
		"searchString" : "string",
		"order" : "string",
		"sortBy" : "string",
		"offset" : "string",
		"limit" : "string",
		"Type" : "string",
		"Communication" : "string",
		"Address" : "string",
		"Owner" : "string",
		"Membership" : "string",
		"AccountsList" : "string",
		"EAgreementRequired" : "string",
		"LastName" : "string",
		"MiddleName" : "string",
		"FirstName" : "string",
		"status" : "string",
		"Lastlogintime" : "string",
		"role_id" : "string",
		"DOB" : "string",
		"Ssn" : "string",
		"TypeName" : "string",
		"DrivingLicenseNumber" : "string",
		"DateOfBirth" : "string",
		"isExists" : "string",
		"Account_id" : "string",
		"accountID" : "string",
		"addressId" : "string",
	}
	Object.freeze(typings);
	
	var primaryKeys = [
					"id",
	];
	Object.freeze(primaryKeys);
	
	var config = {
		mappings : mappings,
		typings : typings,
		primaryKeys : primaryKeys,
		serviceName : "RBObjects",
		tableName : "Organization"
	};
	Object.freeze(config);
	
	return config;
})
