define([],function(){
	var mappings = {
		"AppVersion" : "AppVersion",
		"bankName" : "bankName",
		"bannerURL" : "bannerURL",
		"branchType" : "branchType",
		"businessDays" : "businessDays",
		"currencyCode" : "currencyCode",
		"distanceUnit" : "distanceUnit",
		"errmsg" : "errmsg",
		"facialLicenseServerUrl" : "facialLicenseServerUrl",
		"facialLicenseString" : "facialLicenseString",
		"isUpdate" : "isUpdate",
		"isUpdateMandatory" : "isUpdateMandatory",
		"MainBranchaddressLine1" : "MainBranchaddressLine1",
		"MainBranchaddressLine2" : "MainBranchaddressLine2",
		"MainBranchCity" : "MainBranchCity",
		"MainBranchLatitude" : "MainBranchLatitude",
		"MainBranchLongitude" : "MainBranchLongitude",
		"MainBranchPhone" : "MainBranchPhone",
		"MainBranchServices" : "MainBranchServices",
		"MainBranchState" : "MainBranchState",
		"MainBranchWorkingHours" : "MainBranchWorkingHours",
		"MainBranchzipCode" : "MainBranchzipCode",
		"ocrApiKey" : "ocrApiKey",
		"ocrSecretKey" : "ocrSecretKey",
		"OSType" : "OSType",
		"OSversion" : "OSversion",
		"versionLink" : "versionLink",
		"appStoreLink" : "appStoreLink",
		"playStoreLink" : "playStoreLink",
		"ipadNativeAppLink" : "ipadNativeAppLink",
		"androidTabletNativeAppLink" : "androidTabletNativeAppLink",
		"isLanguageSelectionEnabled" : "isLanguageSelectionEnabled",
		"isBackEndCurencySymbolEnabled" : "isBackEndCurencySymbolEnabled",
		"isCountryCodeEnabled" : "isCountryCodeEnabled",
		"isSortCodeVisible" : "isSortCodeVisible",
		"currenciesSupported" : "currenciesSupported",
		"isUTCDateFormattingEnabled" : "isUTCDateFormattingEnabled",
		"language" : "language",
		"deploymentGeography" : "deploymentGeography",
		"isBusinessBankingEnabled" : "isBusinessBankingEnabled",
		"isAccountAggregationEnabled" : "isAccountAggregationEnabled",
	};
	Object.freeze(mappings);
	
	var typings = {
		"AppVersion" : "string",
		"bankName" : "string",
		"bannerURL" : "string",
		"branchType" : "string",
		"businessDays" : "string",
		"currencyCode" : "string",
		"distanceUnit" : "string",
		"errmsg" : "string",
		"facialLicenseServerUrl" : "string",
		"facialLicenseString" : "string",
		"isUpdate" : "boolean",
		"isUpdateMandatory" : "boolean",
		"MainBranchaddressLine1" : "string",
		"MainBranchaddressLine2" : "string",
		"MainBranchCity" : "string",
		"MainBranchLatitude" : "string",
		"MainBranchLongitude" : "string",
		"MainBranchPhone" : "string",
		"MainBranchServices" : "string",
		"MainBranchState" : "string",
		"MainBranchWorkingHours" : "string",
		"MainBranchzipCode" : "string",
		"ocrApiKey" : "string",
		"ocrSecretKey" : "string",
		"OSType" : "string",
		"OSversion" : "string",
		"versionLink" : "string",
		"appStoreLink" : "string",
		"playStoreLink" : "string",
		"ipadNativeAppLink" : "string",
		"androidTabletNativeAppLink" : "string",
		"isLanguageSelectionEnabled" : "string",
		"isBackEndCurencySymbolEnabled" : "string",
		"isCountryCodeEnabled" : "string",
		"isSortCodeVisible" : "string",
		"currenciesSupported" : "string",
		"isUTCDateFormattingEnabled" : "string",
		"language" : "string",
		"deploymentGeography" : "string",
		"isBusinessBankingEnabled" : "string",
		"isAccountAggregationEnabled" : "string",
	}
	Object.freeze(typings);
	
	var primaryKeys = [
					"OSType",
	];
	Object.freeze(primaryKeys);
	
	var config = {
		mappings : mappings,
		typings : typings,
		primaryKeys : primaryKeys,
		serviceName : "RBObjects",
		tableName : "Application"
	};
	Object.freeze(config);
	
	return config;
})
