define([],function(){
	var mappings = {
		"Id" : "Id",
		"Customer_id" : "Customer_id",
		"CreditScore" : "CreditScore",
		"NumberOfInquiries_6M" : "NumberOfInquiries_6M",
		"NumberOfInquiries_12M" : "NumberOfInquiries_12M",
		"NumberOfInquiries_24M" : "NumberOfInquiries_24M",
		"TotalRevolvingOpenToBuyBalance" : "TotalRevolvingOpenToBuyBalance",
		"UtilizationPercentOfRevolvingTrades" : "UtilizationPercentOfRevolvingTrades",
		"SinceRecentDelinquency_M" : "SinceRecentDelinquency_M",
		"TotalNumberOfDerogatory" : "TotalNumberOfDerogatory",
		"SinceRecentlyFiledCollection_M" : "SinceRecentlyFiledCollection_M",
		"TotalNumberOfTrades" : "TotalNumberOfTrades",
		"TotalNumberOfActiveTrades" : "TotalNumberOfActiveTrades",
		"NumberOfTradesOpened_24M" : "NumberOfTradesOpened_24M",
		"NumberOfTradeswithUtilization" : "NumberOfTradeswithUtilization",
		"OldestOpenPersonalFinanceTrade_M" : "OldestOpenPersonalFinanceTrade_M",
		"LoanToIncomeRatio" : "LoanToIncomeRatio",
		"NumberOfLoanAapplications_24M" : "NumberOfLoanAapplications_24M",
		"DebtToIncomeRatio" : "DebtToIncomeRatio",
		"PrequalifyScore" : "PrequalifyScore",
		"YearsOfMembership" : "YearsOfMembership",
		"AccountsBalance" : "AccountsBalance",
		"Age" : "Age",
		"City" : "City",
		"State" : "State",
		"ZipCode" : "ZipCode",
		"DurationOfStay" : "DurationOfStay",
		"HomeOwnership" : "HomeOwnership",
		"GrossMonthlyIncome" : "GrossMonthlyIncome",
		"AnnualIncome" : "AnnualIncome",
		"createdby" : "createdby",
		"modifiedby" : "modifiedby",
		"createdts" : "createdts",
		"lastmodifiedts" : "lastmodifiedts",
		"synctimestamp" : "synctimestamp",
		"softdeleteflag" : "softdeleteflag",
		"UserName" : "UserName",
		"success" : "success",
		"errmsg" : "errmsg",
		"errorCode" : "errorCode",
		"errorMessage" : "errorMessage",
	};
	Object.freeze(mappings);
	
	var typings = {
		"Id" : "string",
		"Customer_id" : "string",
		"CreditScore" : "string",
		"NumberOfInquiries_6M" : "string",
		"NumberOfInquiries_12M" : "string",
		"NumberOfInquiries_24M" : "string",
		"TotalRevolvingOpenToBuyBalance" : "string",
		"UtilizationPercentOfRevolvingTrades" : "string",
		"SinceRecentDelinquency_M" : "string",
		"TotalNumberOfDerogatory" : "string",
		"SinceRecentlyFiledCollection_M" : "string",
		"TotalNumberOfTrades" : "string",
		"TotalNumberOfActiveTrades" : "string",
		"NumberOfTradesOpened_24M" : "string",
		"NumberOfTradeswithUtilization" : "string",
		"OldestOpenPersonalFinanceTrade_M" : "string",
		"LoanToIncomeRatio" : "string",
		"NumberOfLoanAapplications_24M" : "string",
		"DebtToIncomeRatio" : "string",
		"PrequalifyScore" : "string",
		"YearsOfMembership" : "string",
		"AccountsBalance" : "string",
		"Age" : "string",
		"City" : "string",
		"State" : "string",
		"ZipCode" : "string",
		"DurationOfStay" : "string",
		"HomeOwnership" : "string",
		"GrossMonthlyIncome" : "string",
		"AnnualIncome" : "string",
		"createdby" : "string",
		"modifiedby" : "string",
		"createdts" : "string",
		"lastmodifiedts" : "string",
		"synctimestamp" : "string",
		"softdeleteflag" : "string",
		"UserName" : "string",
		"success" : "string",
		"errmsg" : "string",
		"errorCode" : "string",
		"errorMessage" : "string",
	}
	Object.freeze(typings);
	
	var primaryKeys = [
					"Id",
	];
	Object.freeze(primaryKeys);
	
	var config = {
		mappings : mappings,
		typings : typings,
		primaryKeys : primaryKeys,
		serviceName : "RBObjects",
		tableName : "DigitalProfile"
	};
	Object.freeze(config);
	
	return config;
})
