define([],function(){
	var mappings = {
		"accountNumber" : "accountNumber",
		"accountType" : "accountType",
		"addressId" : "addressId",
		"addressLine1" : "addressLine1",
		"addressLine2" : "addressLine2",
		"addressType" : "addressType",
		"alertsTurnedOn" : "alertsTurnedOn",
		"areAccountStatementTermsAccepted" : "areAccountStatementTermsAccepted",
		"areDepositTermsAccepted" : "areDepositTermsAccepted",
		"bankName" : "bankName",
		"cardNumber" : "cardNumber",
		"city" : "city",
		"country" : "country",
		"currencyCode" : "currencyCode",
		"cvv" : "cvv",
		"dateOfBirth" : "dateOfBirth",
		"default_account_billPay" : "default_account_billPay",
		"default_account_cardless" : "default_account_cardless",
		"default_account_deposit" : "default_account_deposit",
		"default_account_payments" : "default_account_payments",
		"default_account_transfers" : "default_account_transfers",
		"default_from_account_p2p" : "default_from_account_p2p",
		"default_to_account_p2p" : "default_to_account_p2p",
		"email" : "email",
		"errmsg" : "errmsg",
		"isEmailEnabled" : "isEmailEnabled",
		"isPhoneEnabled" : "isPhoneEnabled",
		"isPinSet" : "isPinSet",
		"isPreferredAddress" : "isPreferredAddress",
		"lastlogintime" : "lastlogintime",
		"oldpassword" : "oldpassword",
		"otp" : "otp",
		"password" : "password",
		"phone" : "phone",
		"pin" : "pin",
		"result" : "result",
		"role" : "role",
		"secondaryemail" : "secondaryemail",
		"secondaryemail2" : "secondaryemail2",
		"secondaryphone" : "secondaryphone",
		"secondaryphone2" : "secondaryphone2",
		"ssn" : "ssn",
		"state" : "state",
		"success" : "success",
		"userfirstname" : "userfirstname",
		"userId" : "userId",
		"userImage" : "userImage",
		"userlastname" : "userlastname",
		"userName" : "userName",
		"zipcode" : "zipcode",
		"rating" : "rating",
		"featureRequest" : "featureRequest",
		"description" : "description",
		"default_account_wire" : "default_account_wire",
		"isWireTransferActivated" : "isWireTransferActivated",
		"isWireTransferEligible" : "isWireTransferEligible",
		"userImageURL" : "userImageURL",
		"modifiedByName" : "modifiedByName",
		"addresses" : "addresses",
		"emailIds" : "emailIds",
		"phoneNumbers" : "phoneNumbers",
		"preferredContactMethod" : "preferredContactMethod",
		"preferredContactTime" : "preferredContactTime",
		"deleteAddressID" : "deleteAddressID",
		"deleteCommunicationID" : "deleteCommunicationID",
		"maritalStatus" : "maritalStatus",
		"noOfDependents" : "noOfDependents",
		"spouseFirstName" : "spouseFirstName",
		"spouseLastName" : "spouseLastName",
		"gender" : "gender",
		"showBillPayFromAccPopup" : "showBillPayFromAccPopup",
		"isP2PActivated" : "isP2PActivated",
		"isP2PSupported" : "isP2PSupported",
		"isBillPaySupported" : "isBillPaySupported",
		"isBillPayActivated" : "isBillPayActivated",
		"securityKey" : "securityKey",
		"phoneExtension" : "phoneExtension",
		"phoneCountryCode" : "phoneCountryCode",
		"idmConfig" : "idmConfig",
		"errCode" : "errCode",
		"errorMessage" : "errorMessage",
		"errorCode" : "errorCode",
		"Id" : "Id",
	};
	Object.freeze(mappings);
	
	var typings = {
		"accountNumber" : "string",
		"accountType" : "number",
		"addressId" : "string",
		"addressLine1" : "string",
		"addressLine2" : "string",
		"addressType" : "string",
		"alertsTurnedOn" : "string",
		"areAccountStatementTermsAccepted" : "string",
		"areDepositTermsAccepted" : "string",
		"bankName" : "string",
		"cardNumber" : "string",
		"city" : "string",
		"country" : "string",
		"currencyCode" : "string",
		"cvv" : "string",
		"dateOfBirth" : "string",
		"default_account_billPay" : "string",
		"default_account_cardless" : "string",
		"default_account_deposit" : "string",
		"default_account_payments" : "string",
		"default_account_transfers" : "string",
		"default_from_account_p2p" : "string",
		"default_to_account_p2p" : "string",
		"email" : "string",
		"errmsg" : "string",
		"isEmailEnabled" : "string",
		"isPhoneEnabled" : "string",
		"isPinSet" : "string",
		"isPreferredAddress" : "string",
		"lastlogintime" : "string",
		"oldpassword" : "string",
		"otp" : "string",
		"password" : "string",
		"phone" : "string",
		"pin" : "string",
		"result" : "string",
		"role" : "string",
		"secondaryemail" : "string",
		"secondaryemail2" : "string",
		"secondaryphone" : "string",
		"secondaryphone2" : "string",
		"ssn" : "string",
		"state" : "string",
		"success" : "string",
		"userfirstname" : "string",
		"userId" : "string",
		"userImage" : "string",
		"userlastname" : "string",
		"userName" : "string",
		"zipcode" : "string",
		"rating" : "string",
		"featureRequest" : "string",
		"description" : "string",
		"default_account_wire" : "string",
		"isWireTransferActivated" : "string",
		"isWireTransferEligible" : "string",
		"userImageURL" : "string",
		"modifiedByName" : "string",
		"addresses" : "string",
		"emailIds" : "string",
		"phoneNumbers" : "string",
		"preferredContactMethod" : "string",
		"preferredContactTime" : "string",
		"deleteAddressID" : "string",
		"deleteCommunicationID" : "string",
		"maritalStatus" : "string",
		"noOfDependents" : "string",
		"spouseFirstName" : "string",
		"spouseLastName" : "string",
		"gender" : "string",
		"showBillPayFromAccPopup" : "string",
		"isP2PActivated" : "string",
		"isP2PSupported" : "string",
		"isBillPaySupported" : "string",
		"isBillPayActivated" : "string",
		"securityKey" : "string",
		"phoneExtension" : "string",
		"phoneCountryCode" : "string",
		"idmConfig" : "string",
		"errCode" : "string",
		"errorMessage" : "string",
		"errorCode" : "string",
		"Id" : "string",
	}
	Object.freeze(typings);
	
	var primaryKeys = [
					"userName",
					"userId",
	];
	Object.freeze(primaryKeys);
	
	var config = {
		mappings : mappings,
		typings : typings,
		primaryKeys : primaryKeys,
		serviceName : "RBObjects",
		tableName : "User"
	};
	Object.freeze(config);
	
	return config;
})
